ansible/ansible-dev-environment

src/pip4a/installer.py

To leave git ignored files behind

Copy the collection before building

---

src/pip4a/config.py
src/pip4a/uninstaller.py

Uninstall will now only uninstall the specified collection, not it's collection deps or python deps

Descope uninstall

---

.config/dictionary.txt
src/pip4a/config.py
src/pip4a/installer.py
tests/integration/test_basic.py

Add the ability to install a non-local collection and it's python deps

Install named collection

---

.config/dictionary.txt
src/pip4a/arg_parser.py
src/pip4a/checker.py
src/pip4a/cli.py
src/pip4a/config.py
src/pip4a/inspector.py
src/pip4a/installer.py
src/pip4a/logger.py
src/pip4a/uninstaller.py
src/pip4a/utils.py
tests/integration/test_basic.py

Add `pip4a check` to identify missing collections and python packages

Add `pip4a check` to identify missing collections and python packages

---

.vscode/launch.json
src/pip4a/arg_parser.py
src/pip4a/checker.py
src/pip4a/cli.py
src/pip4a/installer.py
src/pip4a/logger.py
src/pip4a/utils.py

Verbose cleanup

---

src/pip4a/installer.py

Exit if editable and collection is not local

Editable only for non-local collection installation

---

.config/dictionary.txt
src/pip4a/arg_parser.py
src/pip4a/cli.py
src/pip4a/config.py
src/pip4a/installer.py
src/pip4a/uninstaller.py
src/pip4a/utils.py
tests/fixtures/requirements.yml
tests/integration/test_basic.py

Installation using requirements file

---

.vscode/launch.json
src/pip4a/tree.py
tests/unit/test_tree.py

Add a tree generation class for a dep tree later

Add tree class

---

.config/dictionary.txt
.vscode/settings.json
src/pip4a/cli.py
src/pip4a/collection.py
src/pip4a/config.py
src/pip4a/subcommands/checker.py
src/pip4a/subcommands/inspector.py
src/pip4a/subcommands/installer.py
src/pip4a/subcommands/uninstaller.py
src/pip4a/utils.py
tests/fixtures/galaxy.yml
tests/integration/test_basic.py
tests/unit/test_utils.py

Refactor collection, add feedback

---

src/pip4a/subcommands/checker.py
src/pip4a/subcommands/installer.py

Reorder checks, bugfix in install

---

.github/workflows/release.yml
.github/workflows/tox.yml
.pre-commit-config.yaml
pyproject.toml

Related to https://github.com/ansible/ansible-development-environment/issues/59

Set Python 3.10 as minimum version

---

README.md
docs/index.md
pyproject.toml
src/ansible_dev_environment/subcommands/checker.py
tests/integration/test_basic.py

Fixes https://github.com/ansible/ansible-dev-environment/issues/91

Use ade as the command line

---

.github/workflows/tox.yml

Related: https://github.com/ansible/team-devtools/issues/169

Review codecov config

---

codecov.yml

Related to https://github.com/ansible/team-devtools/issues/169

Remove codecov ci required

---

.config/constraints.txt
.config/requirements-docs.in
.readthedocs.yml
docs/index.md
mkdocs.yml
tox.ini

Jira - https://issues.redhat.com/browse/AAP-19818

Suggest adt install

---

.pre-commit-config.yaml
pyproject.toml

- Switch to black precommit
- Update mypy config
- Remove fixme exemption from pylint

CI config updates

---

tox.ini

These don't really make sense any more given the current way coverage is configured.

Remove coverage clean and report, not compatible with current config

---

pyproject.toml

Change the pylint config to match ansible-creator

Update pylint configuration

---

.pre-commit-config.yaml

To compare more easily with other repos

Unquote versions

---

.github/CODEOWNERS

So reviewers is set to the team automatically

Update code owners to devtools

---

.github/release-drafter.yml

Reverts ansible/ansible-dev-environment#189

Revert "chore: Update .github/release-drafter.yml"

---

.github/workflows/tox.yml
go.json

Test the tox workflows being reusable

Test reusable from td

---

pyproject.toml
src/ansible_dev_environment/cli.py
src/ansible_dev_environment/collection.py
src/ansible_dev_environment/output.py
src/ansible_dev_environment/subcommands/installer.py
src/ansible_dev_environment/subcommands/lister.py
src/ansible_dev_environment/subcommands/uninstaller.py
src/ansible_dev_environment/utils.py
tests/unit/test_utils.py

chore: Update pyproject.toml

---

pyproject.toml

Add known first party for sorting in tests

Add known first party

---

.config/dictionary.txt
tests/unit/test_output.py

largely taken from ansible-creator, this will put output.py at 100%

Add tests for output

---

src/ansible_dev_environment/subcommands/installer.py
tests/conftest.py
tests/unit/conftest.py
tests/unit/test_installer.py
tests/unit/test_treemaker.py
tests/unit/test_uninstaller.py

- Includes a little conditional clenaup from #83 
- Tune the installable collection into a fixture since it was done a few times
- Add tests such that the installer module is covered

Complete tests for installer

---

.github/workflows/tox.yml
.pre-commit-config.yaml
pyproject.toml

Related: https://github.com/ansible/team-devtools/issues/229

Add support for py313

---

src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/subcommands/installer.py
tests/conftest.py
tests/unit/test_installer.py

Related: https://issues.redhat.com/browse/AAP-30772

Make seed option implicit and add --no-seed

---

src/ansible_dev_environment/cli.py
tests/unit/test_installer.py

Prevent execution with broken PATH variable
