ansible/ansible-dev-environment

.config/requirements-docs.txt
.github/workflows/tox.yml
.readthedocs.yml
cspell.config.yaml
docs/index.md
mkdocs.yml
pyproject.toml
tox.ini

Related to https://github.com/ansible/ansible-development-environment/issues/59

Setup mkdocs

---

.config/dictionary.txt
src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/cli.py
src/ansible_dev_environment/collection.py
src/ansible_dev_environment/subcommands/installer.py

Enable source installation capabilities, it depends on the `.config/source-requirements.yml` file to pick up dependencies to source install them.
Command example - 
```shell
ade install ".[test]" --venv venv --cpi
```
Attribute added - 
`cpi/ collection-pre-install`
Example _source-requirements.yml_
```yaml
---
collections:
- git+https://github.com/ansible-collections/ansible.utils.git
- git+https://github.com/ansible-collections/ansible.netcommon.git
```
Log -
```
ansible_development_environment install .\[test\] --venv venv --cpi
Note: Source installed collections include: ansible.netcommon and ansible.utils
Note: Installed collections include: ansible.netcommon, ansible.utils, and cisco.ios
Note: All python requirements are installed.
Note: All required system packages are installed. …
```

Allow installation from source-requirements.yml

---

.pre-commit-config.yaml
src/ansible_dev_environment/subcommands/installer.py

The PR:
1. Splits chained `git ls-files` and `ls` commands and executes them separately to copy files from the local directory to the collection build directory (Fixes: #127).
2. Updates `pydoclint` to v0.4.0 in the pre commit config.

Fix installation of local collection in editable mode

---

.config/dictionary.txt
src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/config.py
tests/unit/test_config.py

For RPMs or cases where ADT has already been installed, allow for site packages in the venv
- Add the ability to use the system site package flag for the venv
- Switch from getsitepackages to sysconfig for better identification of the interpreters local siste packages directory
- Add tests
Closes #138 
Closes #139

Add system site package flag

---

src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/subcommands/installer.py
tests/unit/test_installer.py

Having ansible-dev-tools installed in the virtual environment removes one step the user needs to take when setting up a development environment for a playbook collection
This results in a totally isolated development environment for the project in one command.
Tests included
Closes #109

Add ansible-dev-tools install into venv `--ansible-dev-tools`

---

pyproject.toml
src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/collection.py
src/ansible_dev_environment/config.py
src/ansible_dev_environment/output.py
src/ansible_dev_environment/subcommands/installer.py
src/ansible_dev_environment/subcommands/lister.py
src/ansible_dev_environment/subcommands/treemaker.py
src/ansible_dev_environment/tree.py
src/ansible_dev_environment/utils.py
tests/integration/test_basic.py
tests/unit/conftest.py
tests/unit/test_utils.py

`pydoclint` wasn't checking "short" docstrings.  A *short* docstring is a docstring that doesn't have any args in it (or args formatted incorrectly for the chosen format)
- update the pydoclint config
- remediate any issues found
Note: the `show-filenames-in-every-violation-message = true` option makes it easier to click on an error in the VsCode terminal when running pydoclint

Update pydoclint config and fix docstrings

---

.config/requirements-dev.in
.config/requirements-test.in
.gitignore
.vscode/extensions.json
.vscode/settings.json
pyproject.toml
tests/conftest.py
tox.ini

Miscellanious changes related to the devleoper configuration and the coverage configuration.
Some of this is pre-work for the GHA changes related to codecov

Update coverage and developer configuration

---

.config/dictionary.txt
.github/workflows/tox.yml
pyproject.toml
tests/test_root.py
tox.ini

Switch to an aggregate coverage upload

Single coverage upload

---

.config/requirements-test.in
.flake8
.pre-commit-config.yaml
.vscode/extensions.json
.vscode/settings.json
pyproject.toml
src/ansible_dev_environment/subcommands/installer.py
src/ansible_dev_environment/subcommands/treemaker.py
src/ansible_dev_environment/utils.py
tests/unit/conftest.py

Unfortunately it appears the only way to get pydoclint feedback within VsCode is to use it as a flake8 plugin.
- Move the pydoclint config to .flake8
- Replace the pydoclint precommit config w/ flake8
- Add the falke8 extension and cofiguration
- This is only untill ruff has full doc string support
Additionally, ruff`s docstyle was set to match pydoclint which fixed 4 little issues
(it also appears ruff may implement pydoclint instead of ruff, no decision yet https://github.com/astral-sh/ruff/issues/458#issuecomment-2122773827 so I think we're headed in a good direction)

Enable pydoclint via flake 8

---

.gitignore
.vscode/settings.json
pyproject.toml
tox.ini

- Move the lcov file into a dot directory to avoid a new gitignore as it is covered the the default GH python gitignore
- Use the seemingly more common name lcov.info
- Move ingore errors into pypreject.toml
- Set an ENVVAR for the combined file and ref it in the tox commands
- Remove env list for the coverage commands, all other sections have commands 
- Remove unecessary params from tox commands
- Remove uneeded `sh` and `&&` from commands
- Single line the build line

Simplify the coverage configuration

---

.vscode/settings.json

With continuesd testing it has been found the daemon is not reliable

Daemon is not reliable

---

.config/constraints.txt
.config/requirements-test.in
.vscode/settings.json
pyproject.toml
src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/subcommands/inspector.py
src/ansible_dev_environment/subcommands/installer.py
src/ansible_dev_environment/subcommands/lister.py
src/ansible_dev_environment/subcommands/treemaker.py
src/ansible_dev_environment/tree.py
src/ansible_dev_environment/utils.py

- Add pylint to test extras
- Update constrainsts
- Fix newly found errors

Remove useless supressions

---

.github/workflows/tox.yml

Update default python to be 3.12 so it matches what pre-commit ci uses, so pylint results will be the same.

Update default python to latest supported

---

.config/dictionary.txt
src/ansible_dev_environment/__main__.py
src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/cli.py
src/ansible_dev_environment/subcommands/treemaker.py
tests/integration/test_basic.py
tests/test_argparser.py
tests/unit/conftest.py
tests/unit/test_cli.py
tests/unit/test_main.py
tests/unit/test_tree.py
tests/unit/test_treemaker.py

Picking off some low hanging fruit.
Minor run time changes to isolate functionality for ease of testing.

Add some tests

---

.pre-commit-config.yaml
.vscode/settings.json
src/ansible_dev_environment/collection.py
src/ansible_dev_environment/output.py
src/ansible_dev_environment/subcommands/installer.py
src/ansible_dev_environment/subcommands/treemaker.py
src/ansible_dev_environment/tree.py
src/ansible_dev_environment/utils.py

Some quick fixes related to scanner findings
Update ruff in precommit as well to quiet ANN102

Quick fixes

---

.config/dictionary.txt
src/ansible_dev_environment/config.py
tests/unit/test_config.py

Add tests for the config module to cover code paths not previously covered by tests.

Add tests for config

---

src/ansible_dev_environment/subcommands/installer.py
tests/unit/test_installer.py

Includes one small runtime change (bug fix) for installer.

Add some tests for installer

---

pyproject.toml
src/ansible_dev_environment/__main__.py
src/ansible_dev_environment/subcommands/__init__.py
tests/conftest.py
tests/integration/test_basic.py
tests/test_argparser.py
tests/unit/test_cli.py
tests/unit/test_inspector.py
tests/unit/test_installer.py
tests/unit/test_lister.py
tests/unit/test_main.py
tests/unit/test_treemaker.py
tests/unit/test_uninstaller.py

Allow ruff to add future annotations

chore: Update pyproject.toml

---

README.md
docs/index.md
mkdocs.yml

Dear maintainers,
As a part of the [Consolidating Ansible discussion platforms initiative](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812), this PR adds the communication section template defined by the community to the README and the docsite. Similar PRs are now being raised across all the Ansible ecosystem projects.
- If you have your forum group and/or tags related to the project, please add corresponding lines by suggesting changes to the PR.
- If the project is not present on the Ansible forum yet, please check out the existing [tags](https://forum.ansible.com/tags) and [groups](https://forum.ansible.com/g) - use what suits your project. If there is no appropriate tag, please [request one](https://forum.ansible.com/t/requesting-a-forum-group/503/1 …

docs: add Communication section

---

.config/constraints.txt
.config/requirements-test.in
.pre-commit-config.yaml
pyproject.toml
src/ansible_dev_environment/arg_parser.py

From now on we will use `--seed` for installing extra packages when creating the venv. We still support the old argument names but they will be removed in the near future.
Related: https://issues.redhat.com/browse/AAP-30772

Replace -adt/--ansible-dev-tools argument with --seed

---

README.md
docs/index.md
pyproject.toml
src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/cli.py
tests/unit/test_cli.py

From now on, if a virtualenv is not already active, ade will assume the use of .venv environment for all commands and mention this in a warning message.
Related: https://issues.redhat.com/browse/AAP-30772

Make use of .venv environment implicit if none is active

---

src/ansible_dev_environment/arg_parser.py

This is needed because we already have -v and -e options and attempts to use `--ve` were not working due to:
ade: error: ambiguous option: --ve could match --verbose, --version

Remove ambiguous option --ve for providing the virtueanenv name

---

.config/dictionary.txt
.config/requirements-test.in
.pre-commit-config.yaml
docs/index.md
pyproject.toml
src/ansible_dev_environment/config.py
src/ansible_dev_environment/subcommands/installer.py
src/ansible_dev_environment/utils.py
tests/unit/test_config.py
tests/unit/test_installer.py

Adds a huge speed boost in creating virtualenv by taking advantage of uv when it is found as being installed.

Use uv venv instead of python venv when available

---

src/ansible_dev_environment/subcommands/installer.py

Fixes multiple cases where a failure to execute a process gave a cryptic error due to stdout and/or stderr not being displayed.

Ensure we display all information about failed processes

---

.config/dictionary.txt
.config/pydoclint-baseline.txt
.config/requirements-test.in
pyproject.toml
tests/integration/test_basic.py
tests/unit/test_installer.py
tests/unit/test_output.py
tox.ini

- The mock of `shutil.get_terminal_size` was missing the fallback arg and not returning exactly what the src was. This should make it look more like the actual function.
- Add the UV constraint to tox to use the constraints file
- Disable tests requiring pylibssh for python 3.13
ref: https://github.com/python/cpython/blob/9a6b702f3a19251c286588094ba00037c4b2c06e/Lib/shutil.py#L1494

Better mock of get_terminal_width, UV constraints, disable broken tests on py313

---

src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/cli.py
src/ansible_dev_environment/config.py
src/ansible_dev_environment/utils.py
tests/integration/test_basic.py
tests/unit/test_cli.py
tests/unit/test_cli_deprecated.py
tests/unit/test_cli_precedence.py
tests/unit/test_config.py
tests/unit/test_installer.py
tests/unit/test_treemaker.py
tests/unit/test_utils.py

Create a mapping between environment variables and an argparse `dest`.  To preserve a CLI->ENV->default order of precedence we'll look for each of the mapping's option strings in the cli paramters.  If provided on the CLI, ignore the enviroment variable.  If not provided use an enviroment variable if set.
Environment variable are added to their respective attribute help string.
All ADE specific enviroment variables are prefaced with `ADE_` to avoid a conflict with other applicaitons.
This moves  and renames the `SKIP_UV` enviroment variables out to the parser as `ADE_UV` and adds a command line parameter to match (#278) Backward compatible support was added.
This also revises the use of `VIRTUAL_ENV` such that it is the enviroment variable for the `--venv` command line paramter and used …

Add environment variable support for select parameters

---

.config/requirements-test.in
.pre-commit-config.yaml
src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/cli.py
tests/unit/test_cli.py

```
ade --l
--log-append <bool>  --la  -- Append to log file. (choices: true, false) (default: true)                                                                                                           
--log-file <file>    --lf  -- Log file to write to. (default: /home/bthornto/github/ansible-dev-environment/ansible-dev-environment.log)                                                           
--log-level <level>  --ll  -- Log level for file output. (choices: notset, debug, info, warning, error, critical) (default: notset)    
```
docs to be added later with forthcoming docs work
Left as an opt-in for now.
[AAP-30795](https://issues.redhat.com/browse/AAP-30795)

Enable cli tab completion

---

src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/subcommands/installer.py
tests/integration/test_basic.py

Fixes #293 
Allow for a user specified core version relying on the package install to raise any dep conflicts.
We'll install core first if specified to satisfy the ADT dep on core.

Allow user specified ansible-core version

---

src/ansible_dev_environment/arg_parser.py
src/ansible_dev_environment/config.py
tests/integration/test_user_python.py
tests/unit/test_config.py

Fixes #215 
Allow the user to specify a python interpreter name, version or path.  In the case of `uv` the string is just handed over to `uv` to resolve. In the case of `pip` the interpreter needs to be in the path.

Allow user specified python interpreter

---

.github/workflows/tox.yml
tox.ini

Enable devel testing job

---

.config/constraints.txt
.config/pydoclint-baseline.txt
.pre-commit-config.yaml
src/ansible_dev_environment/subcommands/installer.py
src/ansible_dev_environment/utils.py
tests/integration/test_basic.py
tests/unit/test_utils.py

```
ade install -e ".[test]" -v
<...>
Info: Optional dependencies found: /home/bthornto/github/ansible.scm/test-requirements.txt
<...>
```
The format for optional deps if very much like python, in this case we will look for either a `test-requirements.txt` or `requirements-test.txt` file in the root of the collection. It will get passed off a user provided requirements to the dependency resolver.
This was broken in #43 due to the removal off the collection from the config object.
Improved an existing test to ensure it's working
Improved logging to surface optional dependency discovery
Fixes #258

Fix optional dependency installation

---

src/ansible_dev_environment/config.py
src/ansible_dev_environment/subcommands/installer.py
src/ansible_dev_environment/utils.py
tests/unit/test_installer_warning.py
tests/unit/test_utils_dependency_constraint.py

Fixes: #354 
When users specify a specific ansible-core version via `--ansible-core-version`, the subsequent installation of ansible-dev-tools would override the user-specified version due to dependency resolution conflicts. For example, `ansible-core==2.16.0` would be upgraded to `ansible-core==2.19.0` during ansible-dev-tools installation.
This PR implements a dependency-aware installation strategy that preserves user-specified ansible-core versions while providing compatibility warnings:
1. **Installation Order**: Reorder dependency installation to install ansible-dev-tools first, then force-reinstall the user-specified ansible-core version
2. **Dynamic Dependency Detection**: Add `get_dependency_constraint()` utility that uses `pip install --dry-run` to determine ansible-dev-tools' …

Fix ansible-core version preservation during ansible-dev-tools installation

---

.github/workflows/tox.yml

Pins the workflow to team-devtools main commit `d894908cc9005130104c9807b460453c7c2bb398` to circumvent issue with next commit that changes to use astral-uv instead of setup-python action. 
Something in the uv setup is causing macOS with Python 3.10 to hang indefinitely.

Pin tox workflow to circumvent issue with setup-uv and macOS/Python3.10
